name: 'hugo-link-checker'
description: ''
author: 'Tim Buchinger'
branding:
  icon: stop-circle
  color: gray-dark
inputs:
  hugo-options:
    description: 'Options to be passed to the hugo serve command.'
    default: ''
    required: false
  muffet-options:
    description: 'Options to be passed to the muffet command.'
    default: ''
    required: false
  timeout-seconds:
    description: 'The maximum amount of time to spend testing the website before timing out.'
    default: '60'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filter }}