name: Release to Docker Hub Registry

on:
  push:
    tags:
      - "v*.*.*"
  # release:
  #   types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags:
            ${{ secrets.DOCKER_HUB_USERNAME }}/hugo-link-checker:${{ env.TAG }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/hugo-link-checker:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}